apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      nodeSelector: # nodeSelector 추가
        kubernetes.io/hostname: flask # 원하는 노드 이름 지정
      containers:
        - name: flask-pod
          image: 119.197.27.55:5000/flask@sha256:90dc60de280d6f2caf5ff888867cc5d3522774e5d85fbd2a809e9d2b3707bc64
          ports:
            - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: svc-flask
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 443
      targetPort: 7777
      nodePort: 32000
