apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-pod
          image: 119.197.27.55:5000/flask@sha256:0c2413aa6b01312608cf78ba977e9629d8a59d3328fa57945879c0c308dbc385
          ports:
            - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: svc-flask
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 80
      targetPort: 7777
      nodePort: 32000
