apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-pod
          image: 119.197.27.55:5000/flask@sha256:121dfff7f4dc8c19a7f1f4ac1d9ee9a0408bfa87cd14cd55dd9dd499f7078664
          ports:
            - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: svc-flask
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 80
      targetPort: 7777
      nodePort: 32000
